### ISSUE TITLE
Page size is not correct when printing a hidden element

### ISSUE THREAD

**Issue by ineszetter** [madnight/anyprint.js#1]
When trying to print a div with a certain structure I am not able to force the styling or format, hence the output is minimized, which doesnt occur with visible elements
Using Mozilla Developer 89.0b7 & Chrome

![evidencia](https://user-images.githubusercontent.com/45494690/117086862-6a0aab00-ad13-11eb-9df7-b573184113d1.png)

Code attached
[exampleBug.txt](https://github.com/madnight/anyprint.js/files/6424629/exampleBug.txt)

**Comment by madnight** [comment]
Hi @ineszetter,

this repository is not about printing with a device to paper, but about terminal output to stdout/stderr. You might want to report your issue here: https://github.com/ezefdeil/AnyPrint
